env:
  es2020: true
extends:
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  project: ./tsconfig.json
  sourceType: module
plugins:
  - sort-keys-fix
  - import
rules:
  comma-dangle:
    - error
    - always-multiline
  import/no-unresolved:
    - error
    - commonjs: true
  import/order:
    - error
    - alphabetize:
        order: asc
      groups:
        - builtin
        - external
        - - sibling
          - parent
        - index
      newlines-between: always
  sort-keys-fix/sort-keys-fix: error
  '@typescript-eslint/strict-boolean-expressions': error
settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true
